# Generated by Django 4.2.5 on 2023-09-21 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_alter_persontovisit_email_alter_visitor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_signin',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='login_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
