# Generated by Django 4.2.5 on 2023-09-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_visitor_is_signin_visitor_login_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_signout',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
